import re

def validate_quote(quote, original_text):
    """
        Verifies if a specific quote extracted by the AI exists within the source text.

        The function normalizes both the quote and the source text by removing
        excess whitespace and converting them to lowercase to ensure a reliable
        comparison that isn't affected by formatting artifacts.

        Args:
            quote (str): The text snippet or sentence extracted from the policy.
            original_text (str): The full raw text of the PDF policy.

        Returns:
            bool: True if the quote is found within the original text, False otherwise.
    """
    if not quote: return False
    def super_clean(text):
        clean = re.sub(r'[^a-zA-Z0-9]', '', text)
        return clean.lower()
    clean_quote = super_clean(quote)
    clean_original = super_clean(original_text)
    return clean_quote in clean_original


def validate_sql_codes(sql_query, original_text):
    """
        Validates that all CPT/HCPCS codes used in the generated SQL exist in the policy.

        This function acts as a safety guard against "hallucinated" medical codes.
        It extracts all 5-digit sequences from the SQL query and cross-references
        them with all 5-digit sequences found in the original policy text.

        Args:
            sql_query (str): The SQL implementation string generated by the AI.
            original_text (str): The raw text of the policy containing valid codes.

        Returns:
            tuple: (bool, list)
                   - bool: True if all codes in the SQL are valid/found.
                   - list: A list of 'invalid' codes that were found in the SQL but
                           are missing from the source policy.
    """
    codes_in_sql = re.findall(r'\b\d{5}\b', sql_query)
    valid_codes = re.findall(r'\b\d{5}\b', original_text)

    invalid_codes = [code for code in codes_in_sql if code not in valid_codes]
    return len(invalid_codes) == 0, invalid_codes


def validate_rules_report(results, raw_text):
    """
    Validates all extracted rules against the original PDF text.
    Updates the results object with validation flags and prints a status report.
    """
    rules = results.get('rules', [])

    for i, rule in enumerate(rules, 1):
        rule_name = rule.get('rule_name', 'Unknown Rule')
        print(f"\n{'=' * 60}")
        print(f"RULE #{i}: {rule_name}")
        print(f"{'=' * 60}")

        # 1. Validate Quote
        is_quote_valid = validate_quote(rule.get('quote', ''), raw_text)
        if is_quote_valid:
            print(f"  ✅ Quote Validation: Pass")
        else:
            print(f"  ❌ Quote Validation: FAIL")
            print(f"     Expected: \"{rule.get('quote', '')[:100]}...\"")
            print(f"     Action: AI hallucinated or misquoted the source text.")

        # 2. Validate SQL Codes
        is_sql_valid, invalid_codes = validate_sql_codes(rule.get('sql', ''), raw_text)
        if is_sql_valid:
            print(f"  ✅ SQL Code Integrity: Pass (All codes exist in policy)")
        else:
            print(f"  ❌ SQL Code Integrity: FAIL")
            print(f"     Invalid Codes Found: {invalid_codes}")
            print(f"     Action: Remove {invalid_codes} from SQL; they are not in the PDF.")

        rule['quote_valid'] = is_quote_valid
        rule['sql_valid'] = is_sql_valid
        rule['invalid_codes'] = invalid_codes

    print(f"\n{'-' * 60}")
    print(f"Summary: Validation complete for {len(rules)} rules.")

    return results


def generate_html(data):
    """
    Generates an HTML report from policy data.
    Args:
        data (dict): Dictionary containing 'policy_name' and a 'rules' list.
    Returns:
            str: Formatted HTML document string.
    """
    if not data: return "<h1>No Data Found</h1>"
    html = f"<html><body>"
    html += f"<h1>Policy Name: {data.get('policy_name')}</h1>"
    html += "<hr><h3>Rules List:</h3>"
    for rule in data.get('rules', []):
        html += f"""
        <div>
            <h2>Rule Name: {rule.get('rule_name')}</h2>
            <p><b>Description:</b> {rule.get('description')}</p>
            <p><b>SQL-based implementation:</b></p>
            <pre style="background:#eee; padding:10px;">{rule.get('sql')}</pre>
            <p><b>SQL Validation:</b> {rule.get('sql_valid')}</p>
            <p><b>Invalid Codes Found:</b> {rule.get('invalid_codes')}</p>
            <p><b>Logic Confidence:</b> {rule.get('logic_confidence')}</p>
            <p><b>Classification (Rule Type):</b> {rule.get('classification')}</p>
            <p><b>Quote:</b> <i>"{rule.get('quote')}"</i></p>
            <p><b>Quote Validation:</b> {rule.get('quote_valid')}</p>
        </div>
        <hr>
        """

    html += "</body></html>"
    return html
